apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::340703320668:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6VMUVTKD270R
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::340703320668:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-30T20:36:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1804"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 853d4444-0158-41eb-a6f3-987a4941a64d
