apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::340703320668:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TOZXKPV8B7A8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::340703320668:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-31T15:31:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "957"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 87440956-30ca-4e0b-873c-69b3e6373cd3
